### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by qsrenniks** [cwrenniks/xenovirus#38]
- [ ] create bullet decals
- [ ] come up with a main weapon design 
- [ ] Finish issue #35 
- [ ] finish alien animations
- [ ] create alien ai for just the alien we have created
- [ ] finish alien rig when we need it
- [ ] finish texturing the first room you are in
- [ ] model props for the first room
- [ ] polish out the main character controller
- [ ] create dialogue boxes and come up with a more fleshed out story line
- [ ] create ui sprites and art
- [ ] create first deck
- [ ] figure our how to use particle systems to do smoke and atmospheric effects
- [ ] finish up the inventory system
- [ ] create art for the inventory system
